### ISSUE TITLE
OS X El Capitan .app is a PowerPC file? Can't load it.

### ISSUE THREAD

**Issue by thomasgrastein** [iam4x/pokemongo-webspoof#111]
The blank app starts fine on my iPhone, but nothing starts on the mac. It seems that it compiles as a powerpc application, which is not supported after the snow leopard update from apple.

**Comment by zreese** [comment]
I'm having the same issue. How did you end up fixing this?

**Comment by thomasgrastein** [comment]
Hi Zreese, you must download the .app from the link in the readme, and not clone the files from github. They will automatically be in the app. So that when you launch the .app, xcode will start with it, and not the other way around

**Comment by zreese** [comment]
But the compiled binary linked to from the readme is v1.1, which is two days old at this point. I'd like to build a version that has the latest changes.

**Comment by iam4x** [comment]
@zreese Run `$ npm run dev` which will start dev version

**Comment by zreese** [comment]
@iam4x I haven't had any luck with building it through npm, which is why I was wondering if the .app was accessible through the repo.

```
no module found for: transform-es2015-classes
/Users/zreese/Downloads/pokemon/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:91
				p._original_name = key;
				                 ^

TypeError: Cannot set property '_original_name' of undefined
    at /Users/zreese/Downloads/pokemon/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:91:22
    at Array.forEach (native)
    at module.exports (/Users/zreese/Downloads/pokemon/node_modules/babel-preset-save/node_modules/modify-babel-preset/index.js:77:29)
    at Object.<anonymous> (/Users/zreese/Downloads/pokemon/node_modules/babel-preset-save/index.js:3:35)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zreese/Downloads/pokemon/node_modules/babel-core/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

**Comment by iam4x** [comment]
What version of node are you running? Did you run `$ npm install` before?

**Comment by zreese** [comment]
I'm running npm 2.15.5 and node 4.4.5. I did install the package through npm successfully.
