### ISSUE TITLE
(com.electron.pokemongo-webspoof): Service exited with abnormal code: 7

### ISSUE THREAD

**Issue by justvanbloom** [iam4x/pokemongo-webspoof#147]
(com.electron.pokemongo-webspoof): Service exited with abnormal code: 7

**Comment by evannudd** [comment]
Can you provide more information on how to reproduce this error?

**Comment by BigFish87** [comment]
I have the same error. Its shown directly after starting "pokemongo-webspoof".

Nothing else happens. There is no new Windows from pokemongo-webspoof or from Xcode. Its like nothink started.

Here are the full Log for the application start:

24.07.16 10:49:25,765 lsd[297]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
24.07.16 10:49:25,917 launchservicesd[77]: SecTaskLoadEntitlements failed error=22
24.07.16 10:49:25,924 launchservicesd[77]: SecTaskLoadEntitlements failed error=22
24.07.16 10:49:25,954 appleeventsd[49]: SecTaskLoadEntitlements failed error=22
24.07.16 10:49:26,034 pokemongo-webspoof Helper[640]: GVA info: preferred scaler idx 0
24.07.16 10:49:26,078 launchservicesd[77]: SecTaskLoadEntitlements failed error=22
24.07.16 10:49:26,086 lsd[297]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
24.07.16 10:49:26,088 launchservicesd[77]: SecTaskLoadEntitlements failed error=22
24.07.16 10:49:26,105 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x1000000e.pokemongo-webspoof[639]) Service exited with abnormal code: 7


Here are some more details:

OS X 10.11.6
MacBook Pro End2013
Xcode 7.3.1

**Comment by nekoyokoshima** [comment]
I had the same issue. After some investigation, found out the app will not load if the parent directory has a space in it.

`Keiths-MacBook-Pro-2:MacOS keith$ ./pokemongo-webspoof
cp: 2/pokemongo-webspoof.app/Contents/Resources/app/xcode-project: No such file or directory
module.js:442
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/keith/Downloads/pokemongo-webspoof-darwin-x64 2/pokemongo-webspoof.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/Users/keith/Downloads/pokemongo-webspoof-darwin-x64 2/pokemongo-webspoof.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:35:14)
    at process.<anonymous> (/Users/keith/Downloads/pokemongo-webspoof-darwin-x64 2/pokemongo-webspoof.app/Contents/Resources/electron.asar/browser/init.js:61:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:262:26)`

Not Working: pokemongo-webspoof-darwin-x64 2
Working: pokemongo-webspoof-darwin-x64-2

**Comment by iam4x** [comment]
@nekoyokoshima Nice catch, I will investigate more. For the `abnormal code: 7` I have no idea :(

**Comment by BigFish87** [comment]
yep, thats the solution. I have a space in my User dir.....
