### ISSUE TITLE
New web spoof not working

### ISSUE THREAD

**Issue by hhuesca** [iam4x/pokemongo-webspoof#166]
Just downloaded the latest version of the webspoof but it won´t load. Any thoughts?

Awesome work!

**Comment by ferazambuja** [comment]
Same here. How to I run on a debug mode? 
It loads and quits. Doesn't even starts XCode.

**Comment by ferazambuja** [comment]
/pokemongo-webspoof.app/Contents/MacOS/pokemongo-webspoof ; exit;
cp: 2/pokemongo-webspoof.app/Contents/Resources/app/xcode-project: No such file or directory
module.js:440
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/pokemongo-webspoof-darwin-x64 2/pokemongo-webspoof.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/pokemongo-webspoof-darwin-x64 2/pokemongo-webspoof.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:35:14)
    at process.<anonymous> (/pokemongo-webspoof-darwin-x64 2/pokemongo-webspoof.app/Contents/Resources/electron.asar/browser/init.js:61:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (node.js:276:26)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by ferazambuja** [comment]
Deleted everything and redownloaded...it worked :)

**Comment by daniellozynski** [comment]
Also not working for me ;-(

**Comment by SaipanDamashii** [comment]
It doesn't work for me, either.  I double click on the app to launch it, wait forever for it to actually do something, and then next thing I know the icon just disappears from my dock and nothing happens.

**Comment by AbelIngrand** [comment]
Did you follow the How to Update guide https://github.com/iam4x/pokemongo-webspoof/ ?

**Comment by SaipanDamashii** [comment]
No, why would I need to update the app when I haven't even managed to get it running/installed the first time? lol (as sarcastic as that sounds, I'm seriously curious if that's a necessary step)
